# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: ubuntu

stages:
  - build
  - deploy

services:
  - docker:dind

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client docker -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan rzipa.at >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-master:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: TestEnv
    url: https://app.rzipa.at
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploy to dev server"
  environment:
    name: TestEnv
    url: https://dev.app.rzipa.at
  except:
    - master
